/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Variable;
import Servicio.NotacionPolacaServicio;
import Servicio.RegistroVariablesServicio;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WilsonMundo
 */
public class NotacionPolacaVista extends javax.swing.JInternalFrame {

    public boolean VariablesAsignadas = false;
    private ArrayList<Variable> variable = new ArrayList<>();
    private RegistroVariablesServicio variableServicio = new RegistroVariablesServicio();

    /**
     * Creates new form NotacionPolacaVista
     */
    public NotacionPolacaVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jftingreso = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jbResuelveExpression = new javax.swing.JButton();
        jftResultado = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaDibujaArbol = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtPreorden = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtInorden = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtPostOrden = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Validacion Expression");
        setPreferredSize(new java.awt.Dimension(932, 677));

        jftingreso.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jftingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftingresoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton1.setText("Validar Expresión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbResuelveExpression.setBackground(new java.awt.Color(0, 51, 255));
        jbResuelveExpression.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jbResuelveExpression.setText("Resolver Expresión");
        jbResuelveExpression.setEnabled(false);
        jbResuelveExpression.setPreferredSize(new java.awt.Dimension(150, 21));
        jbResuelveExpression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbResuelveExpressionActionPerformed(evt);
            }
        });

        jftResultado.setEditable(false);
        jftResultado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.0000"))));
        jftResultado.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jftResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftResultadoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel1.setText("Resultado");

        jTable1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Variable", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(35);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton2.setText("Nueva Expresión");
        jButton2.setPreferredSize(new java.awt.Dimension(150, 21));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel3.setText("Datos de Variables");

        jScrollPane3.setAutoscrolls(true);

        jtaDibujaArbol.setColumns(20);
        jtaDibujaArbol.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jtaDibujaArbol.setRows(5);
        jScrollPane3.setViewportView(jtaDibujaArbol);

        jTabbedPane1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N

        jLabel2.setText("Preorden ");

        jtPreorden.setColumns(20);
        jtPreorden.setRows(5);
        jScrollPane2.setViewportView(jtPreorden);

        jtInorden.setColumns(20);
        jtInorden.setRows(5);
        jScrollPane4.setViewportView(jtInorden);

        jLabel4.setText("Inorden");

        jLabel5.setText("Postorden ");

        jtPostOrden.setColumns(20);
        jtPostOrden.setRows(5);
        jScrollPane5.setViewportView(jtPostOrden);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Recorridos Del arbol", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbResuelveExpression, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(508, 508, 508)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(395, 395, 395))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jftingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)))
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jftResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(197, 197, 197))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbResuelveExpression, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jftingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftingresoActionPerformed

    private void jbResuelveExpressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbResuelveExpressionActionPerformed

        try {
            if (!(variable.isEmpty()) && variable.size() > 0) {
                if (variableServicio.ExisenVariablesConValorNull(variable)) {
                    JOptionPane.showMessageDialog(this, "Error Existen variables y aun no estan asignadas", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

            }

            NotacionPolacaServicio notacionPolaca = new NotacionPolacaServicio();
            ArrayList<Character> caracteres;
            String expression = jftingreso.getText();
            caracteres = notacionPolaca.RetornaCadenaCaracteres(expression);

            String result = String.valueOf(notacionPolaca.notacionPolacaGeneral(expression, variable));

            if (!(notacionPolaca.getValoresPostorden().isEmpty()) && notacionPolaca.getValoresPostorden().size() > 0) {
                String recorrido = "";
                for (String item : notacionPolaca.getValoresPostorden()) {
                    recorrido = recorrido + item + " ";
                }
                jtPostOrden.setText(recorrido.trim());
            }
             if (!(notacionPolaca.getValoresInOrden().isEmpty()) && notacionPolaca.getValoresInOrden().size() > 0) {
                String recorrido = "";
                for (String item : notacionPolaca.getValoresInOrden()) {
                    recorrido = recorrido + item + " ";
                }
                jtInorden.setText(recorrido.trim());
            }
             if (!(notacionPolaca.getValoresPreOrden().isEmpty()) && notacionPolaca.getValoresPreOrden().size() > 0) {
                String recorrido = "";
                for (String item : notacionPolaca.getValoresPreOrden()) {
                    recorrido = recorrido + item + " ";
                }
                jtPreorden.setText(recorrido.trim());
            }
            jftResultado.setText(result);
            
                
            jtaDibujaArbol.setText("   +\n  / \\\n 5   3");
            jtaDibujaArbol.setEditable(false);

            
        } catch (RuntimeException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error en Resolver Expresión \n"+e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error en Resolver Expresión\n"+e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }


    }//GEN-LAST:event_jbResuelveExpressionActionPerformed

    private void llenarTablaVariables() {
        try {
            // Crear modelo de tabla y establecerlo en el JTable
            DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Variable", "Valor"}, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return column == 1;
                }
            };
            jTable1.setModel(modelo);
            modelo.addTableModelListener(new TableModelListener() {
                @Override
                public void tableChanged(TableModelEvent e) {
                    if (e.getType() == TableModelEvent.UPDATE) {
                        int fila = e.getFirstRow();
                        int columna = e.getColumn();
                        if (columna == 1) { // Columna del valor
                            Object valor = modelo.getValueAt(fila, columna);
                            try {
                                double valorDouble = Double.parseDouble(valor.toString());
                                variable.get(fila).setValor(valorDouble);
                            } catch (NumberFormatException ex) {
                                JOptionPane.showMessageDialog(null, "Ocurrió un error al actualizar la variable\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                                ex.printStackTrace();
                            }
                        }
                    }
                }
            });

            for (Variable tipo : variable) {
                modelo.addRow(new Object[]{tipo.getCaracter(), tipo.getValor()});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al ingresar las variables " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            String dato = jftingreso.getText();
            if (dato == null || dato.equals("") || dato.length() < 0) {
                JOptionPane.showMessageDialog(this, "El dato ingresado no puede ser vacio", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            } else {

                jftingreso.setText(variableServicio.ValidarExpression(dato));
                dato = jftingreso.getText();
                jftingreso.setEditable(false);
                variable = variableServicio.RetonarVariableSinValor(dato);

                if (!(variable.isEmpty()) && variable.size() > 0) {
                    llenarTablaVariables();
                    JOptionPane.showMessageDialog(this, "Existen variables en la Expresión"
                            + "\n ingrese sus respectivos valores", "Ayuda", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "la expresion es valida puede resolver la Expresión" , "Ayuda", JOptionPane.INFORMATION_MESSAGE);
                }
                jbResuelveExpression.setEnabled(true);
            }

        } catch (RuntimeException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error en validar expression\n"+e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error en validar expression\n"+e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jftResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftResultadoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jftingreso.setText("");
        jftingreso.setEditable(true);
        jbResuelveExpression.setEnabled(false);
        variable = new ArrayList<>();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        jftResultado.setText("");
        jtPostOrden.setText("");
        jtInorden.setText("");
        jtPreorden.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbResuelveExpression;
    private javax.swing.JFormattedTextField jftResultado;
    private javax.swing.JFormattedTextField jftingreso;
    private javax.swing.JTextArea jtInorden;
    private javax.swing.JTextArea jtPostOrden;
    private javax.swing.JTextArea jtPreorden;
    private javax.swing.JTextArea jtaDibujaArbol;
    // End of variables declaration//GEN-END:variables
}
